#!/bin/sh

currentId=$(git rev-parse --short HEAD)

cat src/main.js | sed "s/let version = 'DEV'/let version = '${currentId}'/" > tmp && mv tmp src/main.js

ids=$1

if [ -z "$1" ]
then
    echo "Id argument missing."
    exit 1
fi

if [ "$ids" = "all" ]
then
    ids=$(ls config/clasp/clasp_*.json | sed 's/^.*clasp_\(.*\).json/\1/')
fi

for id in $ids
do
    if [ ! -f "config/clasp/clasp_$id.json" ]
    then
        echo "Config not found for id: $id"
        exit 1
    fi
    
    cp config/clasp/clasp_$id.json .clasp.json
    echo "deploy $id"
    npm run-script upload
done

cat src/main.js | sed "s/let version = '${currentId}'/let version = 'DEV'/" > tmp && mv tmp src/main.js
