#!/bin/sh

currentId=$(git rev-parse --short HEAD)

cat src/main.js | sed "s/let version = '[^']*'/let version = '${currentId}'/" > tmp && mv tmp src/main.js

id=$1
length=$(cat document_ids.json | jq '.document_ids | length')

for index in $(seq 0 $(( $length - 1)))
do
	shelfmark=$(cat document_ids.json | jq ".document_ids[$index].shelfmark" | tr -d '"')
	if [ "$id" != "all" ] && [ "$id" = "$shelfmark" ] || [ "$id" = "all" ]
	then
		documentid=$(cat document_ids.json | jq ".document_ids[$index].document_id")
		
		echo "{\"scriptId\":$documentid,\"rootDir\":\"src\"}" > .clasp.json

		echo "deploy $documentid as $shelfmark"
		npm run-script upload
		
		if [ "$id" != "all" ]
		then
			break
		else
			sleep 1
		fi
	fi
done